from typing import Protocol


class ReadableBuffer(Protocol):
    def __buffer__(self, flags: int, /) -> memoryview: ...


def encode(data: ReadableBuffer, /) -> bytes: ...
def decode(data: ReadableBuffer, /, *, strict: bool = False) -> bytes: ...


class Encoder:
    def __init__(self) -> None: ...
    def update(self, data: ReadableBuffer, /) -> bytes: ...
    def finish(self) -> bytes: ...


class Decoder:
    def __init__(self, *, strict: bool = False) -> None: ...
    def update(self, data: ReadableBuffer, /) -> bytes: ...
    def finish(self) -> bytes: ...
